# .github/workflows/hello-world.yml
#The name of the workflow, will be displayed on the Github actions page
name: Test

on: #[push, pull_request]
  pull_request:
    types: [closed]
  push:
    branches:
      - master
      - feature

# list of jobs to execute
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Echo branch
        id: echo_branch
        run:  |
          echo ${{ steps.extract_branch.outputs.branch }}

      - name: Get gitref
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF})"
        id: extract_gitref

      - name: Echo gitref
        id: echo_gitref
        run:  |
          echo ${{ steps.extract_gitref.outputs.branch }}

      - name: Github event_name
        run: |
          echo ${{ github.event_name }}

      - name: Github event
        run: |
          echo ${{ github.event.action }} and ${{ github.event.pull_request.merged }}

      - name: Github push ref
        run: |
          echo ${{ github.event.ref }}

      - name: Get branchref
        shell: bash
        run: echo "##[set-output name=branch;]$( IFS="/" read -ra SPLIT_REF <<< ${GITHUB_REF}; echo ${SPLIT_REF[2]})"
        id: extract_branchref

      - name: Echo gitref
        id: echo_branchref
        run:  |
          echo ${{ steps.extract_branchref.outputs.branch }}