# .github/workflows/hello-world.yml
#The name of the workflow, will be displayed on the Github actions page
name: Test

on: [push, pull_request]
  #push:
  #  branches:
  #    - feature

# list of jobs to execute
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get branch
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Echo branch
        id: echo_branch
        run:  |
          echo ${{ steps.extract_branch.outputs.branch }}

      - name: Get gitref
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF})"
        id: extract_gitref

      - name: Echo gitref
        id: echo_gitref
        run:  |
          echo ${{ steps.extract_gitref.outputs.branch }}

      - name: Github event_name
        run: |
          echo ${{ github.event_name }}

      - name: Github event
        run: |
          echo ${{ github.event.pull_request.action }} and ${{ github.event.pull_request.pull_request.merged }}